eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:      defaultZone: http://localhost:5555/eureka
  instance:
    hostname: localhost
server:  port: 8888
spring:  application:    name: PAYMENT-SERVICE