spring:
  application:
    name: ABC-SERVICE
---
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:5555/eureka
  instance:
    hostname: localhost
    appname: ABC-SERVICE
server:
  port: 8000
---
spring:
    profiles: abc-service-replica01
eureka:
  instance:
    appname: ABC-SERVICE  # ==> This is a instance of ABC-SERVICE
  client:   
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:5555/eureka  
server:
  port: 8001
---
spring:
    profiles: abc-service-replica02
eureka:
  instance:
    appname: ABC-SERVICE  # ==> This is a instance of ABC-SERVICE
  client:   
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:5555/eureka  
server:
  port: 8002
      